<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit37fbc8439b1e4d0940a7390244dfb61b
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'Level_Wp\\Affiliate_Advantage\\' => 29,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Level_Wp\\Affiliate_Advantage\\' => 
        array (
            0 => __DIR__ . '/../..' . '/',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit37fbc8439b1e4d0940a7390244dfb61b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit37fbc8439b1e4d0940a7390244dfb61b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit37fbc8439b1e4d0940a7390244dfb61b::$classMap;

        }, null, ClassLoader::class);
    }
}
